export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const DOWNLOAD_INITIALTODOLIST = 'DOWNLOAD_INITIALTODOLIST';
export const DOWNLOAD_INITIALTODOLIST_START = 'DOWNLOAD_INITIALTODOLIST_START';
export const DOWNLOAD_INITIALTODOLIST_SUCCESS = 'DOWNLOAD_INITIALTODOLIST_SUCCESS';
