export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const DOWNLOAD_INITIALTODOLIST = 'DOWNLOAD_INITIALTODOLIST';
export const DOWNLOAD_INITIALTODOLIST_START = 'DOWNLOAD_INITIALTODOLIST_START';
export const DOWNLOAD_INITIALTODOLIST_SUCCESS = 'DOWNLOAD_INITIALTODOLIST_SUCCESS';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const TODO_CREATE = 'TODO_CREATE';

export const TODOLIST_FETCH_SUCCESS = 'TODOLIST_FETCH_SUCCESS';
